window.GAME_CONFIG = {
  constants: {
    TYPE_SPEED_MS: 35,
    STORY_ADVANCE_DELAY: 1800,
    HERO_REGEN: 3,
    BOSS_REGEN: 4,
    SINGLE_HEAL_RATIO: 0.38,
    GROUP_HEAL_RATIO: 0.24,
    LIMIT_GAIN_TAKEN: 10,
    LIMIT_GAIN_DEALT: 5,
  },

  difficulties: {
    easy: { bossHp: 0.8, bossAtk: 0.9, heroHp: 1.2 },
    normal: { bossHp: 1.0, bossAtk: 1.0, heroHp: 1.0 },
    hard: { bossHp: 1.3, bossAtk: 1.15, heroHp: 0.95 },
  },

  storyScenes: [
    {
      speakerId: null,
      text: "Pada puncak Kampar, naga kuno bangun dari tidurnya...",
    },
    {
      speakerId: "aruna",
      text: "Kami tidak punya pilihan. Jika naga ini lolos, koto kampar di bawah ini akan runtuh.",
    },
    {
      speakerId: "meer",
      text: "Aku bisa membengkokkan api naga ini, tapi aku butuh waktu. Lindungi aku.",
    },
    {
      speakerId: "khade",
      text: "Jangan mati tanpa alasan. Selama aku berdiri, kamu akan tetap bernafas.",
    },
    {
      speakerId: "zabx",
      text: "Biarkan dia fokus padaku. Kamu selesaikan dia dari jarak aman.",
    },
    {
      speakerId: "naga kampar",
      text: "Kau berani menantang pemelihara langit...",
    },
  ],

  characters: {
    soldier: {
      id: "soldier",
      name: "Aruna",
      role: "Physical DPS",
      maxHp: 150,
      maxMp: 60,
      atk: 34,
      def: 14,
      mag: 6,
      spd: 12,
      skills: [
        {
          id: "basicSlash",
          name: "Basic Attack",
          cost: 0,
          target: "enemy",
          type: "physical",
          power: 0.9,
          description: "Serangan andalan ketika MP rendah.",
        },
        {
          id: "powerSlash",
          name: "Power Slash",
          cost: 14,
          cooldown: 2,
          target: "enemy",
          type: "physical",
          power: 1.4,
          description: "Pukulan fisik berat yang memberikan damage kuat.",
        },
        {
          id: "armorBreak",
          name: "Armor Break",
          cost: 16,
          cooldown: 3,
          target: "enemy",
          type: "physical",
          power: 1.1,
          debuff: { defDown: 0.2, duration: 2 },
          description:
            "Serangan yang mengurangi pertahanan naga selama 2 giliran.",
        },
        {
          id: "rally",
          name: "Rally",
          cost: 10,
          cooldown: 2,
          target: "allies",
          type: "buff",
          buff: { atkUp: 0.2, duration: 2 },
          description:
            "Membangkitkan semangat sekutu, meningkatkan serangan selama 2 giliran.",
        },
        {
          id: "markPrey",
          name: "Mark Prey",
          cost: 12,
          cooldown: 3,
          target: "enemy",
          type: "physical",
          power: 0.9,
          debuff: { mark: true, duration: 3 },
          description:
            "Menandai naga, membuatnya rentan terhadap serangan sihir api.",
        },
        {
          id: "skyCleave",
          name: "Sky Cleave",
          cost: 0,
          target: "enemy",
          type: "physical",
          power: 2.2,
          requiresLimit: 100,
          cooldown: 0,
          description: "Limit: lompatan heroik yang membelah sisik naga.",
        },
      ],
    },

    mage: {
      id: "mage",
      name: "Meer",
      role: "Magic DPS",
      maxHp: 110,
      maxMp: 120,
      atk: 10,
      def: 10,
      mag: 40,
      spd: 14,
      skills: [
        {
          id: "arcaneBolt",
          name: "Arcane Bolt",
          cost: 12,
          cooldown: 1,
          target: "enemy",
          type: "magic",
          power: 1.3,
          description: "Tembakan energi murni yang presisi.",
        },
        {
          id: "firestorm",
          name: "Firestorm",
          cost: 22,
          cooldown: 3,
          target: "all-enemies",
          type: "magic",
          power: 1.1,
          element: "fire",
          description:
            "Badai api AoE yang membakar naga dan meninggalkan bara menyala.",
          dot: { amount: 6, duration: 2 },
        },
        {
          id: "manaSurge",
          name: "Mana Surge",
          cost: 18,
          cooldown: 3,
          target: "self",
          type: "buff",
          buff: { magUp: 0.3, duration: 2 },
          description:
            "Menyalurkan energi untuk meningkatkan kekuatan sihir selama 2 giliran.",
        },
        {
          id: "weakSpark",
          name: "Weak Spark",
          cost: 6,
          target: "enemy",
          type: "magic",
          power: 0.8,
          description: "Percikan ringan untuk menghemat mana.",
        },
        {
          id: "timeWarp",
          name: "Time Warp",
          cost: 16,
          cooldown: 4,
          target: "allies",
          type: "buff",
          buff: { spdUp: 0.2, duration: 2 },
          description:
            "Memanipulasi waktu untuk mempercepat gerakan sekutu selama 2 giliran.",
        },
        {
          id: "meteorFlare",
          name: "Meteor Flare",
          cost: 0,
          cooldown: 0,
          target: "enemy",
          type: "magic",
          power: 2.6,
          element: "fire",
          requiresLimit: 100,
          description:
            "Limit: memanggil bintang berapi yang merobek sisik obsidian.",
        },
      ],
    },

    healer: {
      id: "healer",
      name: "Khade",
      role: "Support",
      maxHp: 140,
      maxMp: 90,
      atk: 12,
      def: 16,
      mag: 24,
      spd: 10,
      skills: [
        {
          id: "singleHeal",
          name: "Single Heal",
          cost: 14,
          cooldown: 1,
          target: "ally",
          type: "heal",
          healRatio: 0.38,
          description: "Memulihkan HP dalam jumlah besar untuk satu sekutu.",
        },
        {
          id: "groupHeal",
          name: "Group Heal",
          cost: 18,
          cooldown: 2,
          target: "allies",
          type: "heal",
          healRatio: 0.24,
          description: "Memulihkan HP moderat untuk semua sekutu.",
        },
        {
          id: "cleanse",
          name: "Cleanse",
          cost: 12,
          cooldown: 1,
          target: "ally",
          type: "cleanse",
          description: "Menghilangkan efek debuff berbahaya dari satu sekutu.",
        },
        {
          id: "lightStrike",
          name: "Light Strike",
          cost: 4,
          target: "enemy",
          type: "magic",
          power: 0.6,
          description: "Serangan lembut sihir cahaya.",
        },
        {
          id: "divineLight",
          name: "Divine Light",
          cost: 0,
          cooldown: 0,
          target: "allies",
          type: "heal",
          healRatio: 0.45,
          requiresLimit: 100,
          description:
            "Limit: memandikan sekutu dengan cahaya penyembuh dan memperbaiki luka.",
        },
      ],
    },

    tank: {
      id: "tank",
      name: "Zabx",
      role: "Defender",
      maxHp: 220,
      maxMp: 60,
      atk: 18,
      def: 28,
      mag: 8,
      spd: 8,
      skills: [
        {
          id: "bash",
          name: "Bash",
          cost: 8,
          cooldown: 1,
          target: "enemy",
          type: "physical",
          power: 1.0,
          description: "Hantaman perisai yang bisa menggoyahkan naga.",
          debuff: { dmgDown: 0.15, spdDown: 0.2, duration: 2 },
        },
        {
          id: "guard",
          name: "Guard",
          cost: 10,
          cooldown: 2,
          target: "self",
          type: "buff",
          buff: { guard: 0.4, duration: 1 },
          description:
            "Bersiap untuk dampak, mengurangi damage yang masuk untuk giliran ini.",
        },
        {
          id: "taunt",
          name: "Provoke",
          cost: 12,
          cooldown: 3,
          target: "self",
          type: "taunt",
          duration: 2,
          description: "Menarik fokus naga selama 2 giliran.",
        },
        {
          id: "shieldWall",
          name: "Shield Wall",
          cost: 16,
          cooldown: 4,
          target: "allies",
          type: "buff",
          buff: { guardTeam: 0.2, duration: 2 },
          description:
            "Mengangkat perisai untuk seluruh tim, mengurangi damage selama 2 giliran.",
        },
        {
          id: "stoneBulwark",
          name: "Stone Bulwark",
          cost: 0,
          cooldown: 0,
          target: "allies",
          type: "buff",
          buff: { guardTeam: 0.35, duration: 2 },
          requiresLimit: 100,
          description:
            "Limit: membentuk tembok tak tertembus untuk melindungi semua orang.",
        },
      ],
    },

    dragon: {
      id: "dragon",
      name: "Naga Kampar",
      gifName: "dragon",
    },
  },

  boss: {
    id: "boss",
    name: "Naga Kampar",
    maxHp: 2200,
    maxMp: 200,
    atk: 42,
    def: 24,
    mag: 36,
    spd: 11,
    skills: [
      {
        id: "crushingClaw",
        name: "Crushing Claw",
        cost: 0,
        type: "physical",
        power: 1.1,
        pattern: "single",
        weight: 4,
      },
      {
        id: "fieryRend",
        name: "Fiery Rend",
        cost: 22,
        type: "magic",
        power: 1.8,
        splashPower: 0.7,
        pattern: "single-splash",
        weight: 3,
      },
      {
        id: "cinderWave",
        name: "Cinder Wave",
        cost: 18,
        type: "magic",
        power: 1.15,
        pattern: "aoe",
        weight: 3,
      },
      {
        id: "obliterate",
        name: "Obliterate",
        cost: 32,
        type: "physical",
        power: 2.4,
        pattern: "single",
        weight: 1,
      },
      {
        id: "scaleHarden",
        name: "Scale Harden",
        cost: 16,
        type: "buff",
        pattern: "self",
        buff: { defUp: 0.3, duration: 2 },
        weight: 2,
      },
      {
        id: "roaringSilence",
        name: "Roaring Silence",
        cost: 20,
        type: "magic",
        pattern: "silence",
        weight: 2,
      },
      {
        id: "recklessFury",
        name: "Reckless Fury",
        cost: 10,
        type: "buff",
        pattern: "berserk",
        buff: { atkUp: 0.35, defDown: 0.2, duration: 2 },
        weight: 2,
      },
    ],
  },

  messages: {
    tipArmorBreak:
      "Tip: Armor Break menurunkan DEF naga—serang dengan serangan fisik saat lemah.",
    tipBurning:
      "Tip: Api terus menyala setelah aksi. Jaga agar api tetap hidup untuk damage berkelanjutan.",
    tipGuard:
      "Tip: Guard dan Shield Wall menahan pukulan berat; gunakan sebelum serangan besar.",

    dragonActing: "Naga sedang bergerak...",
    heroTurn: "${heroName} giliran",

    skillUsed:
      "${user} menggunakan ${skill} pada ${target} sebesar ${damage} damage.",
    executeBonus: "${skill} menggigit lebih keras terhadap musuh yang lemah!",

    healed: "${user} menyembuhkan ${target} sebesar ${amount}.",

    buffAllies: "${user} menggunakan ${skill} untuk memperkuat sekutu.",
    cleansed: "${user} membersihkan ${target}.",
    provoke: "${user} memprovokasi naga!",

    burningDamage: "Bara api membakar ${target} sebesar ${damage}.",
    burningFades: "Api di sekitar naga padam.",

    dragonScorched: "Naga membakar ${target} sebesar ${damage} damage.",
    dragonBlast:
      "Naga melepaskan ledakan api pada ${target} sebesar ${damage} damage.",
    dragonSplash: "Api percikan membakar ${target} sebesar ${damage} damage.",
    dragonHarden: "Naga mengeraskan sisiknya dan menghilangkan kelemahan.",
    dragonBerserk: "Naga memeluk kegilaan, menukar pertahanan dengan kekuatan!",
    dragonSilence: "${target} diselimuti oleh auman yang membungkam!",
    dragonObliterate:
      "Naga menggunakan serangan menghancurkan pada ${target} sebesar ${damage} damage.",
    dragonBasicAttack:
      "Naga menyerang ${target} dengan serangan dasar sebesar ${damage} damage.",

    dragonWindup:
      "Naga menghirup dalam-dalam, api berkumpul di tenggorokannya!",
    dragonUnleash:
      "Naga melepaskan kekuatannya dalam auman yang menyala-nyala!",
    dragonPhase2: "Naga mengeraskan sisiknya, mengubah polanya!",
    dragonPhase3:
      "Naga menjadi berserk, bertarung dengan kegilaan yang ceroboh!",
    dragonEnraged: "${bossName} marah! Damagenya melonjak.",
    dragonProvoked: "Naga diprovokasi dan fokus pada ${target}!",

    victory: "Naga runtuh di bawah taktikmu.",
    defeat: "Timmu jatuh oleh amarah naga.",
  },
};
