window.GAME_CONFIG = {
  constants: {
    TYPE_SPEED_MS: 35,
    STORY_ADVANCE_DELAY: 1800,
    HERO_REGEN: 3,
    BOSS_REGEN: 4,
    SINGLE_HEAL_RATIO: 0.38,
    GROUP_HEAL_RATIO: 0.24,
    LIMIT_GAIN_TAKEN: 10,
    LIMIT_GAIN_DEALT: 5,
    STAGGER_MAX: 100,
    STAGGER_DECAY_PER_BOSS_TURN: 8,
    STAGGERED_TURNS: 1,
    STAGGERED_DAMAGE_BONUS: 0.25,
    COUNTER_STAGGER_BONUS: 14,
    WINDUP_INTERRUPT_STAGGER: 25,
  },

  difficulties: {
    easy: { bossHp: 0.8, bossAtk: 0.9, heroHp: 1.2, staggerTaken: 1.15 },
    normal: { bossHp: 1.0, bossAtk: 1.0, heroHp: 1.0, staggerTaken: 1.0 },
    hard: { bossHp: 1.3, bossAtk: 1.15, heroHp: 0.95, staggerTaken: 0.9 },
  },

  blessings: [
    {
      id: "breakerCharm",
      name: "Breaker Charm",
      description: "+5 break damage and +15% part damage.",
      effects: { staggerBonus: 5, partDamageBonus: 0.15 },
    },
    {
      id: "focusShard",
      name: "Focus Shard",
      description: "Heroes start with 20% limit and gain +2 MP each turn.",
      effects: { startLimit: 20, mpRegenBonus: 2 },
    },
    {
      id: "vanguardOath",
      name: "Vanguard Oath",
      description: "+8% max HP and team guard for the first 2 turns.",
      effects: { maxHpBonus: 0.08, startGuardTeam: 0.12, guardDuration: 2 },
    },
  ],

  challenges: [
    {
      id: "none",
      name: "Standard",
      description: "No extra modifier.",
      effects: {},
    },
    {
      id: "timeAttack",
      name: "Time Attack",
      description: "Win before turn 180 in Skirmish or 500 in Campaign.",
      effects: { turnLimit: 180, campaignTurnLimit: 500 },
    },
    {
      id: "scorchedSky",
      name: "Scorched Sky",
      description: "Boss damage +12%, hero HP -4%.",
      effects: { bossAtkBonus: 0.12, heroHpBonus: -0.04 },
    },
    {
      id: "scarcity",
      name: "Scarcity",
      description: "Fewer items and lower MP recovery.",
      effects: { itemCountPenalty: 1, mpRegenPenalty: 1 },
    },
  ],

  campaign: {
    recoveryHpRatio: 0.35,
    recoveryMpRatio: 0.3,
    encounters: [
      {
        id: "outerRidge",
        name: "Ridge Wyrm",
        bossHp: 0.55,
        bossAtk: 0.85,
        partIntegrity: 0.68,
        message: "Encounter 1/3: Ridge Wyrm blocks the ascent.",
      },
      {
        id: "stormPeak",
        name: "Storm Naga",
        bossHp: 0.78,
        bossAtk: 1,
        partIntegrity: 0.86,
        message: "Encounter 2/3: Storm Naga guards the crater.",
      },
      {
        id: "kamparHeart",
        name: "Naga Kampar",
        bossHp: 1,
        bossAtk: 1.08,
        partIntegrity: 1,
        message: "Encounter 3/3: Naga Kampar reveals its true strength.",
      },
    ],
  },

  consumables: [
    {
      id: "potion",
      name: "Potion",
      count: 2,
      target: "ally",
      type: "heal",
      healRatio: 0.35,
      description: "Restore 35% HP to one hero.",
    },
    {
      id: "ether",
      name: "Ether",
      count: 1,
      target: "ally",
      type: "mp",
      amount: 35,
      description: "Restore 35 MP to one hero.",
    },
    {
      id: "focusCrystal",
      name: "Focus Crystal",
      count: 1,
      target: "ally",
      type: "limit",
      amount: 35,
      description: "Grant 35% limit to one hero.",
    },
    {
      id: "smokeBomb",
      name: "Smoke Bomb",
      count: 1,
      target: "allies",
      type: "guardTeam",
      amount: 0.22,
      duration: 1,
      description: "Reduce team damage for 1 turn.",
    },
  ],

  comboChains: [
    {
      id: "sunderStrike",
      name: "Sunder Strike",
      sequence: ["armorBreak", "powerSlash"],
      damageBonus: 0.2,
      staggerBonus: 12,
    },
    {
      id: "markedFlame",
      name: "Marked Flame",
      sequence: ["markPrey", "firestorm"],
      damageBonus: 0.16,
      partDamageBonus: 0.12,
    },
    {
      id: "bulwarkCrash",
      name: "Bulwark Crash",
      sequence: ["shieldWall", "bash"],
      staggerBonus: 18,
    },
    {
      id: "meteorSignal",
      name: "Meteor Signal",
      sequence: ["markPrey", "meteorFlare"],
      damageBonus: 0.24,
      staggerBonus: 16,
    },
  ],

  storyScenes: [
    {
      speakerId: null,
      text: "Pada puncak Kampar, naga kuno bangun dari tidurnya...",
    },
    {
      speakerId: "aruna",
      text: "Kami tidak punya pilihan. Jika naga ini lolos, koto kampar di bawah ini akan runtuh.",
    },
    {
      speakerId: "meer",
      text: "Aku bisa membengkokkan api naga ini, tapi aku butuh waktu. Lindungi aku.",
    },
    {
      speakerId: "khade",
      text: "Jangan mati tanpa alasan. Selama aku berdiri, kamu akan tetap bernafas.",
    },
    {
      speakerId: "zabx",
      text: "Biarkan dia fokus padaku. Kamu selesaikan dia dari jarak aman.",
    },
    {
      speakerId: "naga kampar",
      text: "Kau berani menantang pemelihara langit...",
    },
  ],

  characters: {
    soldier: {
      id: "soldier",
      name: "Aruna",
      role: "Physical DPS",
      maxHp: 150,
      maxMp: 60,
      atk: 34,
      def: 14,
      mag: 6,
      spd: 12,
      skills: [
        {
          id: "basicSlash",
          name: "Basic Attack",
          cost: 0,
          target: "enemy",
          type: "physical",
          power: 0.9,
          stagger: 8,
          description: "Serangan andalan ketika MP rendah.",
        },
        {
          id: "powerSlash",
          name: "Power Slash",
          cost: 14,
          cooldown: 2,
          target: "enemy",
          type: "physical",
          power: 1.4,
          stagger: 18,
          description: "Pukulan fisik berat yang memberikan damage kuat.",
        },
        {
          id: "armorBreak",
          name: "Armor Break",
          cost: 16,
          cooldown: 3,
          target: "enemy",
          type: "physical",
          power: 1.1,
          stagger: 22,
          debuff: { defDown: 0.2, duration: 2 },
          counterplay: {
            patterns: ["self", "aoe"],
            staggerBonus: 18,
            interruptWindup: true,
          },
          description:
            "Serangan yang mengurangi pertahanan naga selama 2 giliran.",
        },
        {
          id: "rally",
          name: "Rally",
          cost: 10,
          cooldown: 2,
          target: "allies",
          type: "buff",
          buff: { atkUp: 0.2, duration: 2 },
          description:
            "Membangkitkan semangat sekutu, meningkatkan serangan selama 2 giliran.",
        },
        {
          id: "markPrey",
          name: "Mark Prey",
          cost: 12,
          cooldown: 3,
          target: "enemy",
          type: "physical",
          power: 0.9,
          stagger: 10,
          debuff: { mark: true, duration: 3 },
          description:
            "Menandai naga, membuatnya rentan terhadap serangan sihir api.",
        },
        {
          id: "skyCleave",
          name: "Sky Cleave",
          cost: 0,
          target: "enemy",
          type: "physical",
          power: 2.2,
          stagger: 35,
          requiresLimit: 100,
          cooldown: 0,
          counterplay: {
            patterns: ["single", "single-splash", "aoe", "self", "berserk"],
            staggerBonus: 20,
            interruptWindup: true,
          },
          description: "Limit: lompatan heroik yang membelah sisik naga.",
        },
      ],
    },

    mage: {
      id: "mage",
      name: "Meer",
      role: "Magic DPS",
      maxHp: 110,
      maxMp: 120,
      atk: 10,
      def: 10,
      mag: 40,
      spd: 14,
      skills: [
        {
          id: "arcaneBolt",
          name: "Arcane Bolt",
          cost: 12,
          cooldown: 1,
          target: "enemy",
          type: "magic",
          power: 1.3,
          stagger: 10,
          description: "Tembakan energi murni yang presisi.",
        },
        {
          id: "firestorm",
          name: "Firestorm",
          cost: 22,
          cooldown: 3,
          target: "all-enemies",
          type: "magic",
          power: 1.1,
          stagger: 14,
          element: "fire",
          description:
            "Badai api AoE yang membakar naga dan meninggalkan bara menyala.",
          dot: { amount: 6, duration: 2 },
        },
        {
          id: "manaSurge",
          name: "Mana Surge",
          cost: 18,
          cooldown: 3,
          target: "self",
          type: "buff",
          buff: { magUp: 0.3, duration: 2 },
          description:
            "Menyalurkan energi untuk meningkatkan kekuatan sihir selama 2 giliran.",
        },
        {
          id: "weakSpark",
          name: "Weak Spark",
          cost: 6,
          target: "enemy",
          type: "magic",
          power: 0.8,
          stagger: 6,
          description: "Percikan ringan untuk menghemat mana.",
        },
        {
          id: "timeWarp",
          name: "Time Warp",
          cost: 16,
          cooldown: 4,
          target: "allies",
          type: "buff",
          buff: { spdUp: 0.2, duration: 2 },
          description:
            "Memanipulasi waktu untuk mempercepat gerakan sekutu selama 2 giliran.",
        },
        {
          id: "meteorFlare",
          name: "Meteor Flare",
          cost: 0,
          cooldown: 0,
          target: "enemy",
          type: "magic",
          power: 2.6,
          element: "fire",
          stagger: 32,
          requiresLimit: 100,
          description:
            "Limit: memanggil bintang berapi yang merobek sisik obsidian.",
        },
      ],
    },

    healer: {
      id: "healer",
      name: "Khade",
      role: "Support",
      maxHp: 140,
      maxMp: 90,
      atk: 12,
      def: 16,
      mag: 24,
      spd: 10,
      skills: [
        {
          id: "singleHeal",
          name: "Single Heal",
          cost: 14,
          cooldown: 1,
          target: "ally",
          type: "heal",
          healRatio: 0.38,
          description: "Memulihkan HP dalam jumlah besar untuk satu sekutu.",
        },
        {
          id: "groupHeal",
          name: "Group Heal",
          cost: 18,
          cooldown: 2,
          target: "allies",
          type: "heal",
          healRatio: 0.24,
          description: "Memulihkan HP moderat untuk semua sekutu.",
        },
        {
          id: "cleanse",
          name: "Cleanse",
          cost: 12,
          cooldown: 1,
          target: "ally",
          type: "cleanse",
          description: "Menghilangkan efek debuff berbahaya dari satu sekutu.",
        },
        {
          id: "lightStrike",
          name: "Light Strike",
          cost: 4,
          target: "enemy",
          type: "magic",
          power: 0.6,
          stagger: 8,
          description: "Serangan lembut sihir cahaya.",
        },
        {
          id: "divineLight",
          name: "Divine Light",
          cost: 0,
          cooldown: 0,
          target: "allies",
          type: "heal",
          healRatio: 0.45,
          requiresLimit: 100,
          description:
            "Limit: memandikan sekutu dengan cahaya penyembuh dan memperbaiki luka.",
        },
      ],
    },

    tank: {
      id: "tank",
      name: "Zabx",
      role: "Defender",
      maxHp: 220,
      maxMp: 60,
      atk: 18,
      def: 28,
      mag: 8,
      spd: 8,
      skills: [
        {
          id: "bash",
          name: "Bash",
          cost: 8,
          cooldown: 1,
          target: "enemy",
          type: "physical",
          power: 1.0,
          stagger: 24,
          description: "Hantaman perisai yang bisa menggoyahkan naga.",
          debuff: { dmgDown: 0.15, spdDown: 0.2, duration: 2 },
          counterplay: {
            patterns: ["single", "single-splash", "berserk"],
            staggerBonus: 14,
          },
        },
        {
          id: "guard",
          name: "Guard",
          cost: 10,
          cooldown: 2,
          target: "self",
          type: "buff",
          buff: { guard: 0.4, duration: 1 },
          counterplay: {
            patterns: ["single"],
            guardBoost: 0.15,
          },
          description:
            "Bersiap untuk dampak, mengurangi damage yang masuk untuk giliran ini.",
        },
        {
          id: "taunt",
          name: "Provoke",
          cost: 12,
          cooldown: 3,
          target: "self",
          type: "taunt",
          duration: 2,
          counterplay: {
            patterns: ["single", "single-splash"],
            forceTaunt: true,
          },
          description: "Menarik fokus naga selama 2 giliran.",
        },
        {
          id: "shieldWall",
          name: "Shield Wall",
          cost: 16,
          cooldown: 4,
          target: "allies",
          type: "buff",
          buff: { guardTeam: 0.2, duration: 2 },
          counterplay: {
            patterns: ["aoe", "single-splash"],
            guardBoost: 0.1,
          },
          description:
            "Mengangkat perisai untuk seluruh tim, mengurangi damage selama 2 giliran.",
        },
        {
          id: "stoneBulwark",
          name: "Stone Bulwark",
          cost: 0,
          cooldown: 0,
          target: "allies",
          type: "buff",
          buff: { guardTeam: 0.35, duration: 2 },
          requiresLimit: 100,
          counterplay: {
            patterns: ["aoe", "single-splash"],
            guardBoost: 0.1,
          },
          description:
            "Limit: membentuk tembok tak tertembus untuk melindungi semua orang.",
        },
      ],
    },

    dragon: {
      id: "dragon",
      name: "Naga Kampar",
      gifName: "dragon",
    },
  },

  boss: {
    id: "boss",
    name: "Naga Kampar",
    maxHp: 1900,
    maxMp: 200,
    atk: 42,
    def: 24,
    mag: 36,
    spd: 11,
    parts: [
      {
        id: "head",
        name: "Head",
        maxIntegrity: 150,
        disabledSkillIds: ["roaringSilence"],
        breakStagger: 18,
        effectLabel: "Disables Silence",
        breakMessage: "Kepala naga retak. Roaring Silence tidak bisa dipakai.",
      },
      {
        id: "wings",
        name: "Wings",
        maxIntegrity: 170,
        disabledSkillIds: ["cinderWave"],
        breakStagger: 20,
        effectLabel: "Disables Cinder Wave",
        breakMessage: "Sayap naga patah. Cinder Wave kehilangan daya.",
      },
      {
        id: "claws",
        name: "Claws",
        maxIntegrity: 160,
        disabledSkillIds: ["obliterate"],
        breakStagger: 22,
        effectLabel: "Disables Obliterate",
        breakMessage: "Cakar naga hancur. Obliterate tidak bisa dipakai.",
      },
      {
        id: "tail",
        name: "Tail",
        maxIntegrity: 140,
        disabledSkillIds: ["fieryRend"],
        breakStagger: 16,
        effectLabel: "Disables Fiery Rend",
        breakMessage: "Ekor naga terputus. Fiery Rend tidak bisa dipakai.",
      },
    ],
    skills: [
      {
        id: "crushingClaw",
        name: "Crushing Claw",
        cost: 0,
        type: "physical",
        power: 1.1,
        pattern: "single",
        weight: 4,
      },
      {
        id: "fieryRend",
        name: "Fiery Rend",
        cost: 22,
        type: "magic",
        power: 1.8,
        splashPower: 0.7,
        pattern: "single-splash",
        weight: 3,
      },
      {
        id: "cinderWave",
        name: "Cinder Wave",
        cost: 18,
        type: "magic",
        power: 1.15,
        pattern: "aoe",
        weight: 3,
      },
      {
        id: "obliterate",
        name: "Obliterate",
        cost: 32,
        type: "physical",
        power: 2.4,
        pattern: "single",
        weight: 1,
      },
      {
        id: "scaleHarden",
        name: "Scale Harden",
        cost: 16,
        type: "buff",
        pattern: "self",
        buff: { defUp: 0.3, duration: 2 },
        weight: 2,
      },
      {
        id: "roaringSilence",
        name: "Roaring Silence",
        cost: 20,
        type: "magic",
        pattern: "silence",
        weight: 2,
      },
      {
        id: "recklessFury",
        name: "Reckless Fury",
        cost: 10,
        type: "buff",
        pattern: "berserk",
        buff: { atkUp: 0.35, defDown: 0.2, duration: 2 },
        weight: 2,
      },
    ],
  },

  messages: {
    tipArmorBreak:
      "Tip: Armor Break menurunkan DEF naga—serang dengan serangan fisik saat lemah.",
    tipBurning:
      "Tip: Api terus menyala setelah aksi. Jaga agar api tetap hidup untuk damage berkelanjutan.",
    tipGuard:
      "Tip: Guard dan Shield Wall menahan pukulan berat; gunakan sebelum serangan besar.",
    blessingChosen: "Blessing aktif: ${blessingName}.",
    challengeActive: "Challenge aktif: ${challengeName}.",
    campaignEncounter: "${encounterName}",

    dragonActing: "Naga sedang bergerak...",
    heroTurn: "${heroName} giliran",

    skillUsed:
      "${user} menggunakan ${skill} pada ${target} sebesar ${damage} damage.",
    executeBonus: "${skill} menggigit lebih keras terhadap musuh yang lemah!",

    healed: "${user} menyembuhkan ${target} sebesar ${amount}.",

    buffAllies: "${user} menggunakan ${skill} untuk memperkuat sekutu.",
    cleansed: "${user} membersihkan ${target}.",
    provoke: "${user} memprovokasi naga!",

    burningDamage: "Bara api membakar ${target} sebesar ${damage}.",
    burningFades: "Api di sekitar naga padam.",

    dragonScorched: "Naga membakar ${target} sebesar ${damage} damage.",
    dragonBlast:
      "Naga melepaskan ledakan api pada ${target} sebesar ${damage} damage.",
    dragonSplash: "Api percikan membakar ${target} sebesar ${damage} damage.",
    dragonHarden: "Naga mengeraskan sisiknya dan menghilangkan kelemahan.",
    dragonBerserk: "Naga memeluk kegilaan, menukar pertahanan dengan kekuatan!",
    dragonSilence: "${target} diselimuti oleh auman yang membungkam!",
    dragonObliterate:
      "Naga menggunakan serangan menghancurkan pada ${target} sebesar ${damage} damage.",
    dragonBasicAttack:
      "Naga menyerang ${target} dengan serangan dasar sebesar ${damage} damage.",

    dragonWindup:
      "Naga menghirup dalam-dalam, api berkumpul di tenggorokannya!",
    dragonUnleash:
      "Naga melepaskan kekuatannya dalam auman yang menyala-nyala!",
    dragonPhase2: "Naga mengeraskan sisiknya, mengubah polanya!",
    dragonPhase3:
      "Naga menjadi berserk, bertarung dengan kegilaan yang ceroboh!",
    dragonEnraged: "${bossName} marah! Damagenya melonjak.",
    dragonProvoked: "Naga diprovokasi dan fokus pada ${target}!",
    bossStaggered:
      "${bossName} kehilangan keseimbangan! Aksi berikutnya batal dan damage masuk meningkat.",
    bossStaggerSkip: "${bossName} masih terhuyung dan gagal bertindak.",
    bossIntentCanceled:
      "${bossName} kehilangan momentum dan gagal menyelesaikan serangannya.",
    bossIntentCountered: "${user} membaca intent naga dan menyiapkan counter.",
    bossWindupInterrupted:
      "${user} memecah konsentrasi naga. Serangan charge batal.",
    bossHardenCountered:
      "Sisik naga sudah retak. Scale Harden gagal terbentuk.",
    bossTauntLocked: "${user} mengunci fokus naga pada dirinya.",
    bossShieldPrepared:
      "${user} menyiapkan pertahanan tepat sebelum serangan besar.",
    bossPartBroken: "${partName} hancur.",
    bossPartInterrupted:
      "${partName} hancur dan intent naga kehilangan fungsi.",
    comboTriggered: "Combo aktif: ${comboName}.",
    itemUsed: "${user} menggunakan ${itemName} pada ${target}.",
    itemAllies: "${user} menggunakan ${itemName} untuk seluruh tim.",
    challengeFailed: "Challenge gagal. Waktu habis.",
    encounterClear:
      "${encounterName} runtuh. Tim memulihkan sebagian kekuatan sebelum lanjut.",
    campaignVictory: "Semua penjaga Kampar telah dikalahkan.",

    victory: "Naga runtuh di bawah taktikmu.",
    defeat: "Timmu jatuh oleh amarah naga.",
  },
};
